### ISSUE TITLE
Integration Test Error

### ISSUE THREAD

**Issue by dangell7** [XRPLF/xrpl.js#2094]
I tried to follow the config for running the integration tests.

Cannot find module 'xrpl-local' or its corresponding type declarations.

```
lerna run test:integration --stream

lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 1 package: "npm run test:integration"
xrpl: > xrpl@2.3.1 test:integration /Users/dustedfloor/projects/xrpl-labs/xrpl.js/packages/xrpl
xrpl: > TS_NODE_PROJECT=tsconfig.build.json nyc mocha ./test/integration/**/*.ts ./test/integration/*.ts
xrpl: TSError: ⨯ Unable to compile TypeScript:
xrpl: test/integration/requests/accountChannels.ts(3,40): error TS2307: Cannot find module 'xrpl-local' or its corresponding type declarations.
xrpl:     at createTSError (/Users/dustedfloor/projects/xrpl-labs/xrpl.js/node_modules/ts-node/src/index.ts:820:12)
xrpl:     at reportTSError (/Users/dustedfloor/projects/xrpl-labs/xrpl.js/node_modules/ts-node/src/index.ts:824:19)
xrpl:     at getOutput (/Users/dustedfloor/projects/xrpl-labs/xrpl.js/node_modules/ts-node/src/index.ts:1014:36)
xrpl:     at Object.compile (/Users/dustedfloor/projects/xrpl-labs/xrpl.js/node_modules/ts-node/src/index.ts:1322:43)
xrpl:     at Module.m._compile (/Users/dustedfloor/projects/xrpl-labs/xrpl.js/node_modules/ts-node/src/index.ts:1454:30)
xrpl:     at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
xrpl:     at require.extensions.<computed> (/Users/dustedfloor/projects/xrpl-labs/xrpl.js/node_modules/ts-node/src/index.ts:1458:12)
xrpl:     at Object.<anonymous> (/Users/dustedfloor/projects/xrpl-labs/xrpl.js/node_modules/append-transform/index.js:64:4)
xrpl:     at Module.load (internal/modules/cjs/loader.js:950:32)
xrpl:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
xrpl:     at Module.require (internal/modules/cjs/loader.js:974:19)
xrpl:     at require (internal/modules/cjs/helpers.js:101:18)
xrpl:     at Object.exports.requireOrImport (/Users/dustedfloor/projects/xrpl-labs/xrpl.js/node_modules/mocha/lib/nodejs/esm-utils.js:49:16)
xrpl:     at async Object.exports.loadFilesAsync (/Users/dustedfloor/projects/xrpl-labs/xrpl.js/node_modules/mocha/lib/nodejs/esm-utils.js:91:20)
xrpl:     at async singleRun (/Users/dustedfloor/projects/xrpl-labs/xrpl.js/node_modules/mocha/lib/cli/run-helpers.js:125:3)
xrpl:     at async Object.exports.handler (/Users/dustedfloor/projects/xrpl-labs/xrpl.js/node_modules/mocha/lib/cli/run.js:370:5)
xrpl: =============================== Coverage summary ===============================
xrpl: Statements   : Unknown% ( 0/0 )
xrpl: Branches     : Unknown% ( 0/0 )
xrpl: Functions    : Unknown% ( 0/0 )
xrpl: Lines        : Unknown% ( 0/0 )
xrpl: ================================================================================
xrpl: npm ERR! code ELIFECYCLE
xrpl: npm ERR! errno 1
xrpl: npm ERR! xrpl@2.3.1 test:integration: `TS_NODE_PROJECT=tsconfig.build.json nyc mocha ./test/integration/**/*.ts ./test/integration/*.ts`
xrpl: npm ERR! Exit status 1
xrpl: npm ERR! 
xrpl: npm ERR! Failed at the xrpl@2.3.1 test:integration script.
xrpl: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
xrpl: npm ERR! A complete log of this run can be found in:
xrpl: npm ERR!     /Users/dustedfloor/.npm/_logs/2022-09-13T05_29_05_136Z-debug.log
lerna ERR! npm run test:integration exited 1 in 'xrpl'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xrpl.js@ test:integration: `lerna run test:integration --stream`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xrpl.js@ test:integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dustedfloor/.npm/_logs/2022-09-13T05_29_05_164Z-debug.log

```

**Comment by dangell7** [comment]
yes

**Comment by dangell7** [comment]
`npm -g i npm@7` npm 6 was removing the xrpl-local on build

**Comment by dangell7** [comment]
Switched from `brew` managing node to `nvm` solved my issue further. `npm` was "reverted" by brew to v6 after ios update.. Works on M1.
