### ISSUE TITLE
Cannot delete EmailHash field.

### ISSUE THREAD

**Issue by develoQ** [XRPLF/xrpl.js#2150]
The EmailHash field cannot be deleted in an AccountSet transaction.

The Domain field can be deleted by setting it to an empty string.

I think the EmailHash field should be able to be deleted by setting it to an empty string as well.

```js
import { Client, Wallet } from "xrpl";

const main = async () => {
  const client = new Client("wss://s.devnet.rippletest.net:51233/");
  const wallet = Wallet.generate()
  await client.connect();

  await client.fundWallet(wallet)
  await client.submitAndWait({
    TransactionType: 'AccountSet',
    Account: wallet.classicAddress,
    EmailHash: '',
  }, { wallet })
  await client.disconnect();
};

main();
```

```sh
Error: Invalid Hash length 0
    at Hash128.Hash [as constructor] (/Users/tequ/project/xrpl-test/node_modules/ripple-binary-codec/src/types/hash.ts:14:13)
    at new Hash128 (/Users/tequ/project/xrpl-test/node_modules/ripple-binary-codec/src/types/hash-128.ts:12:5)
    at Function.Hash.from (/Users/tequ/project/xrpl-test/node_modules/ripple-binary-codec/src/types/hash.ts:29:14)
    at /Users/tequ/project/xrpl-test/node_modules/ripple-binary-codec/src/types/st-object.ts:127:52
    at Array.forEach (<anonymous>)
    at Function.STObject.from (/Users/tequ/project/xrpl-test/node_modules/ripple-binary-codec/src/types/st-object.ts:126:12)
    at serializeObject (/Users/tequ/project/xrpl-test/node_modules/ripple-binary-codec/src/binary.ts:70:22)
    at signingData (/Users/tequ/project/xrpl-test/node_modules/ripple-binary-codec/src/binary.ts:90:10)
    at encodeForSigning (/Users/tequ/project/xrpl-test/node_modules/ripple-binary-codec/src/index.ts:49:10)
    at computeSignature (/Users/tequ/project/xrpl-test/node_modules/xrpl/src/Wallet/index.ts:530:31)
```

**Comment by pdp2121** [comment]
Thanks for addressing this issue! We are working on fixing it. Will keep you updated!
